variables:
  JAVA_IMAGE_NAME: hk215/notes-backend
  JAVA_IMAGE_TAG: latest
  GCP_PROJECT_ID: guess-game-381115
  GKE_CLUSTER_NAME: notes-cluster

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build -t $JAVA_IMAGE_NAME:$JAVA_IMAGE_TAG -f ./Dockerfile .
    - docker push $JAVA_IMAGE_NAME:$JAVA_IMAGE_TAG
deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud config set container/cluster $GKE_CLUSTER_NAME
    - gcloud config set compute/zone us-east1-c
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone us-east1-c --project $GCP_PROJECT_ID
    - kubectl apply -f ./k8s/k8java-deployment.yml
    - kubectl apply -f ./k8s/k8java-service.yml
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/cloud/deploy.yaml
    - kubectl apply -f ./k8s/ingress-service.yml
